# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6]
        use_openmp : ['true', 'false']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install numpy
        sudo apt-get install -y libopenblas-dev
    - name: Install cyanure
      run: |
        if ${{matrix.use_openmp == 'true'}}; then
          python setup_cyanure_openblas.py install
        else
          python setup_cyanure_openblas_no_openmp.py install
        fi
